// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
)

type Category struct {
	CategoryID int32
	Name       string
}

type Product struct {
	ID          int32
	Name        string
	Description sql.NullString
	Price       string
	CategoryID  sql.NullInt32
	ImageUrl    sql.NullString
}
