// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package database

import (
	"context"
)

const getProduct = `-- name: GetProduct :one
SELECT id, name, description, price, category_id, image_url FROM Products limit 1
`

func (q *Queries) GetProduct(ctx context.Context) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.CategoryID,
		&i.ImageUrl,
	)
	return i, err
}
